include $(GOROOT)/src/Make.inc

TARG=rater
GOFILES=\
	rater.go\
	registration/registration.go\
	storage/interface.go\
	storage/kyoto_storage.go\
	storage/redis_storage.go\
	timestamps/timestamps.go\

include $(GOROOT)/src/Make.cmd
