kind: pipeline
type: docker
name: unit tests

workspace:
  path: /cgrates

steps:
- name: unit
  pull: never
  image: cgrates-integration
  commands:
  - docker-entrypoint.sh
  - ./test.sh

kind: pipeline
type: docker
name: default

workspace:
  path: /cgrates

steps:
- name: integration
  pull: never
  image: cgrates-integration
  commands:
  - docker-entrypoint.sh
  - ./integration_test.sh

- name: notify
  image: drillster/drone-email
  settings:
    from: cgrates.test01@gmail.com
    host: smtp.gmail.com
    username: cgrates.test01
    recipients:
      - alexandru.tripon@itsyscom.com
  when:
    status: [ changed, failure ]