kind: pipeline
type: docker
name: unit

workspace:
  path: /cgrates

steps:
- name: unit
  pull: never
  image: cgrates-integration
  commands:
  - docker-entrypoint.sh
  - ./test.sh
- name: notify
  pull: never
  image: trial97/drone-email
  settings:
    from: cgrates.test01@gmail.com
    credentials:
      from_secret: credentials
    token:
      from_secret: token
  when:
    status: [ changed, failure ]


---
kind: pipeline
type: docker
name: default

workspace:
  path: /cgrates

steps:
- name: integration
  pull: never
  image: cgrates-integration
  commands:
  - docker-entrypoint.sh
  - ./integration_test.sh

- name: notify
  pull: never
  image: trial97/drone-email
  settings:
    from: cgrates.test01@gmail.com
    credentials:
      from_secret: credentials
    token:
      from_secret: token
  when:
    status: [ changed, failure ]

depends_on:
- unit
