kind: pipeline
type: docker
name: unit

workspace:
  path: /go/src/github.com/cgrates/cgrates/

steps:
- name: unit
  pull: never
  image: cgrates-integration
  commands:
  - go version
  - ./test.sh
- name: notify
  pull: never
  image: drillster/drone-email
  settings:
    from.address: cgrates.dronebot@gmail.com
    from.name: DroneEmail
    host: smtp.gmail.com
    username: 
      from_secret: email_username
    password:
      from_secret: email_password
    subject: >
      [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
      ({{ commit.branch }})
    body: 
      file:///go/src/github.com/cgrates/cgrates/drone_template.html
    recipients_file: recipients
  when:
    status:
    - failure

---
kind: pipeline
type: docker
name: integration-internal


workspace:
  path: /go/src/github.com/cgrates/cgrates/

steps:
- name: integration-internal
  pull: never
  image: cgrates-integration
  commands:
  - data/docker/integration/docker-entrypoint.sh
  - ./integration_test.sh -dbtype=*internal
  failure: ignore
- name: notify
  pull: never
  image: drillster/drone-email
  settings:
    from.address: cgrates.dronebot@gmail.com
    from.name: DroneEmail
    host: smtp.gmail.com
    username: 
      from_secret: email_username
    password:
      from_secret: email_password
    subject: >
      [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
      ({{ commit.branch }})
    body: 
      file:///go/src/github.com/cgrates/cgrates/drone_template.html
    recipients_file: recipients
  when:
    status:
    - failure

---
kind: pipeline
type: docker
name: integration-mysql


workspace:
  path: /go/src/github.com/cgrates/cgrates/

steps:
- name: integration-mysql
  pull: never
  image: cgrates-integration
  commands:
  - data/docker/integration/docker-entrypoint.sh
  - ./integration_test.sh -dbtype=*mysql
  failure: ignore
- name: notify
  pull: never
  image: drillster/drone-email
  settings:
    from.address: cgrates.dronebot@gmail.com
    from.name: DroneEmail
    host: smtp.gmail.com
    username: 
      from_secret: email_username
    password:
      from_secret: email_password
    subject: >
      [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
      ({{ commit.branch }})
    body: 
      file:///go/src/github.com/cgrates/cgrates/drone_template.html
    recipients_file: recipients
  when:
    status:
    - failure

---
kind: pipeline
type: docker
name: integration-mongo


workspace:
  path: /go/src/github.com/cgrates/cgrates/

steps:
- name: integration-mongo
  pull: never
  image: cgrates-integration
  commands:
  - data/docker/integration/docker-entrypoint.sh
  - ./integration_test.sh -dbtype=*mongo
  failure: ignore
- name: notify
  pull: never
  image: drillster/drone-email
  settings:
    from.address: cgrates.dronebot@gmail.com
    from.name: DroneEmail
    host: smtp.gmail.com
    username: 
      from_secret: email_username
    password:
      from_secret: email_password
    subject: >
      [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
      ({{ commit.branch }})
    body: 
      file:///go/src/github.com/cgrates/cgrates/drone_template.html
    recipients_file: recipients
  when:
    status:
    - failure

---
kind: pipeline
type: docker
name: integration-postgres


workspace:
  path: /go/src/github.com/cgrates/cgrates/

steps:
- name: integration-postgres
  pull: never
  image: cgrates-integration
  commands:
  - data/docker/integration/docker-entrypoint.sh
  - ./integration_test.sh -dbtype=*postgres
  failure: ignore
- name: notify
  pull: never
  image: drillster/drone-email
  settings:
    from.address: cgrates.dronebot@gmail.com
    from.name: DroneEmail
    host: smtp.gmail.com
    username: 
      from_secret: email_username
    password:
      from_secret: email_password
    subject: >
      [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
      ({{ commit.branch }})
    body: 
      file:///go/src/github.com/cgrates/cgrates/drone_template.html
    recipients_file: recipients
  when:
    status:
    - failure