#! /bin/sh
#
# $Id$

PKG=cgrates

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#
# quoting from the policy:
#     Any necessary prompting should almost always be confined to the
#     post-installation script, and should be protected with a conditional
#     so that unnecessary prompting doesn't happen if a package's
#     installation fails and the `postinst' is called with `abort-upgrade',
#     `abort-remove' or `abort-deconfigure'.

case "$1" in

	configure)
		adduser --quiet --system --group --disabled-password --shell /bin/false --home /run/cgrates --gecos "CGRateS" cgrates || true
		chown cgrates:cgrates /var/lib/cgrates/
		chown cgrates:cgrates /var/lib/cgrates/internal_db/
		chown cgrates:cgrates /var/lib/cgrates/internal_db/datadb/
		chown cgrates:cgrates /var/lib/cgrates/internal_db/backup/
		chown cgrates:cgrates /var/lib/cgrates/internal_db/backup/datadb/
		chown cgrates:cgrates /var/lib/cgrates/internal_db/stordb/
		chown cgrates:cgrates /var/lib/cgrates/internal_db/backup/stordb/
		chown cgrates:cgrates /var/spool/cgrates/
		chown cgrates:cgrates /var/spool/cgrates/analyzers/
		chown cgrates:cgrates /var/spool/cgrates/ees/
		chown cgrates:cgrates /var/spool/cgrates/loader/
		chown cgrates:cgrates /var/spool/cgrates/loader/in/
		chown cgrates:cgrates /var/spool/cgrates/loader/out/
		chown cgrates:cgrates /var/spool/cgrates/ers/
		chown cgrates:cgrates /var/spool/cgrates/ers/in/
		chown cgrates:cgrates /var/spool/cgrates/ers/out/
		chown cgrates:cgrates /var/spool/cgrates/failed_posts/
		chown cgrates:cgrates /var/spool/cgrates/tpe/
		chown root:adm /var/log/cgrates
		chmod 775 /var/log/cgrates
        ;;

	abort-upgrade|abort-remove|abort-deconfigure)

	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#
