package utils

const (
	VERSION             =     "0.9.1rc3"
	POSTGRES 		= "postgres"
	MYSQL    		= "mysql"
	MONGO    		= "mongo"
	REDIS    		= "redis"
	LOCALHOST                = "127.0.0.1"
	FSCDR_FILE_CSV           = "freeswitch_file_csv"
	FSCDR_HTTP_JSON          = "freeswitch_http_json"
	NOT_IMPLEMENTED          = "not implemented"
	PREPAID                  = "prepaid"
	POSTPAID                 = "postpaid"
	PSEUDOPREPAID            = "pseudoprepaid"
	RATED                    = "rated"
	ERR_NOT_IMPLEMENTED      = "NOT_IMPLEMENTED"
	ERR_SERVER_ERROR         = "SERVER_ERROR"
	ERR_NOT_FOUND            = "NOT_FOUND"
	ERR_MANDATORY_IE_MISSING = "MANDATORY_IE_MISSING"
	ERR_DUPLICATE            = "DUPLICATE"
	TBL_TP_TIMINGS           = "tp_timings"
	TBL_TP_DESTINATIONS      = "tp_destinations"
	TBL_TP_RATES             = "tp_rates"
	TBL_TP_DESTINATION_RATES = "tp_destination_rates"
	TBL_TP_DESTRATE_TIMINGS  = "tp_destrate_timings"
	TBL_TP_RATE_PROFILES     = "tp_rate_profiles"
	TBL_TP_ACTIONS           = "tp_actions"
	TBL_TP_ACTION_TIMINGS    = "tp_action_timings"
	TBL_TP_ACTION_TRIGGERS   = "tp_action_triggers"
	TBL_TP_ACCOUNT_ACTIONS   = "tp_account_actions"
	TIMINGS_CSV           = "Timings.csv"
	DESTINATIONS_CSV      = "Destinations.csv"
	RATES_CSV             = "Rates.csv"
	DESTINATION_RATES_CSV = "DestinationRates.csv"
	DESTRATE_TIMINGS_CSV  = "DestinationRateTimings.csv"
	RATE_PROFILES_CSV     = "RatingProfiles.csv"
	ACTIONS_CSV           = "Actions.csv"
	ACTION_TIMINGS_CSV    = "ActionTimings.csv"
	ACTION_TRIGGERS_CSV   = "ActionTriggers.csv"
	ACCOUNT_ACTIONS_CSV   = "AccountActions.csv"
	ROUNDING_UP = "up"
	ROUNDING_MIDDLE = "middle"
        ROUNDING_DOWN = "down"
)
