/*
Real-time Online/Offline Charging System (OCS) for Telecom & ISP environments
Copyright (C) ITsysCOM GmbH

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>
*/

// Code generated by generate_replicator; DO NOT EDIT.

package apis

import (
	"fmt"
	"time"

	"github.com/cgrates/birpc/context"
	"github.com/cgrates/cgrates/engine"
	"github.com/cgrates/cgrates/utils"
)

// ReplicatorSv1 exports DataDB methods as RPC endpoints for replication.
type ReplicatorSv1 struct {
	ping
	dm    *engine.DataManager
	admin *AdminSv1
}

// NewReplicatorSv1 creates a new ReplicatorSv1.
func NewReplicatorSv1(dm *engine.DataManager, admin *AdminSv1) *ReplicatorSv1 {
	return &ReplicatorSv1{dm: dm, admin: admin}
}

func (r *ReplicatorSv1) GetAccount(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *utils.Account) error {
	engine.UpdateReplicationFilters(utils.AccountPrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaAccounts)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetAccountDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetStatQueue(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *engine.StatQueue) error {
	engine.UpdateReplicationFilters(utils.StatQueuePrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaStatQueues)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetStatQueueDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetFilter(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *engine.Filter) error {
	engine.UpdateReplicationFilters(utils.FilterPrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaFilters)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetFilterDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetThreshold(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *engine.Threshold) error {
	engine.UpdateReplicationFilters(utils.ThresholdPrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaThresholds)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetThresholdDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetThresholdProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *engine.ThresholdProfile) error {
	engine.UpdateReplicationFilters(utils.ThresholdProfilePrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaThresholdProfiles)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetThresholdProfileDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetStatQueueProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *engine.StatQueueProfile) error {
	engine.UpdateReplicationFilters(utils.StatQueueProfilePrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaStatQueueProfiles)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetStatQueueProfileDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetTrendProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *utils.TrendProfile) error {
	engine.UpdateReplicationFilters(utils.TrendProfilePrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaTrendProfiles)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetTrendProfileDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetResource(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *utils.Resource) error {
	engine.UpdateReplicationFilters(utils.ResourcesPrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaResources)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetResourceDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetResourceProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *utils.ResourceProfile) error {
	engine.UpdateReplicationFilters(utils.ResourceProfilesPrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaResourceProfiles)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetResourceProfileDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetIPAllocations(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *utils.IPAllocations) error {
	engine.UpdateReplicationFilters(utils.IPAllocationsPrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaIPAllocations)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetIPAllocationsDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetIPProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *utils.IPProfile) error {
	engine.UpdateReplicationFilters(utils.IPProfilesPrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaIPProfiles)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetIPProfileDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetRankingProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *utils.RankingProfile) error {
	engine.UpdateReplicationFilters(utils.RankingProfilePrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaRankingProfiles)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetRankingProfileDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetRouteProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *utils.RouteProfile) error {
	engine.UpdateReplicationFilters(utils.RouteProfilePrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaRouteProfiles)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetRouteProfileDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetAttributeProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *utils.AttributeProfile) error {
	engine.UpdateReplicationFilters(utils.AttributeProfilePrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaAttributeProfiles)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetAttributeProfileDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetChargerProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *utils.ChargerProfile) error {
	engine.UpdateReplicationFilters(utils.ChargerProfilePrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaChargerProfiles)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetChargerProfileDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetRateProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *utils.RateProfile) error {
	engine.UpdateReplicationFilters(utils.RateProfilePrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaRateProfiles)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetRateProfileDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) GetActionProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *utils.ActionProfile) error {
	engine.UpdateReplicationFilters(utils.ActionProfilePrefix, args.TenantID.TenantID(), utils.IfaceAsString(args.APIOpts[utils.RemoteHostOpt]))
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaActionProfiles)
	if err != nil {
		return err
	}
	rcv, err := dataDB.GetActionProfileDrv(ctx, args.Tenant, args.ID)
	if err != nil {
		return err
	}
	*reply = *rcv
	return nil
}

func (r *ReplicatorSv1) SetAccount(ctx *context.Context, args *utils.AccountWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaAccounts)
	if err != nil {
		return err
	}
	if err := dataDB.SetAccountDrv(ctx, args.Account); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetThresholdProfile(ctx *context.Context, args *engine.ThresholdProfileWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaThresholdProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.SetThresholdProfileDrv(ctx, args.ThresholdProfile); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetThresholdProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheThresholdProfiles, args.TenantID(), "", &args.FilterIDs, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetThreshold(ctx *context.Context, args *engine.ThresholdWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaThresholds)
	if err != nil {
		return err
	}
	if err := dataDB.SetThresholdDrv(ctx, args.Threshold); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetThreshold> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheThresholds, args.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetTrendProfile(ctx *context.Context, args *utils.TrendProfileWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaTrendProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.SetTrendProfileDrv(ctx, args.TrendProfile); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetTrendProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheTrendProfiles, args.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetTrend(ctx *context.Context, args *utils.TrendWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaTrends)
	if err != nil {
		return err
	}
	if err := dataDB.SetTrendDrv(ctx, args.Trend); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetTrend> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheTrends, args.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetStatQueueProfile(ctx *context.Context, args *engine.StatQueueProfileWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaStatQueueProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.SetStatQueueProfileDrv(ctx, args.StatQueueProfile); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetStatQueueProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheStatQueueProfiles, args.TenantID(), "", &args.FilterIDs, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetFilter(ctx *context.Context, args *engine.FilterWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaFilters)
	if err != nil {
		return err
	}
	if err := dataDB.SetFilterDrv(ctx, args.Filter); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetFilter> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheFilters, args.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetResourceProfile(ctx *context.Context, args *utils.ResourceProfileWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaResourceProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.SetResourceProfileDrv(ctx, args.ResourceProfile); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetResourceProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheResourceProfiles, args.TenantID(), "", &args.FilterIDs, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetResource(ctx *context.Context, args *utils.ResourceWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaResources)
	if err != nil {
		return err
	}
	if err := dataDB.SetResourceDrv(ctx, args.Resource); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetResource> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheResources, args.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetIPProfile(ctx *context.Context, args *utils.IPProfileWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaIPProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.SetIPProfileDrv(ctx, args.IPProfile); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetIPProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheIPProfiles, args.TenantID(), "", &args.FilterIDs, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetIPAllocations(ctx *context.Context, args *utils.IPAllocationsWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaIPAllocations)
	if err != nil {
		return err
	}
	if err := dataDB.SetIPAllocationsDrv(ctx, args.IPAllocations); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetIPAllocations> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheIPAllocations, args.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetRankingProfile(ctx *context.Context, args *utils.RankingProfileWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaRankingProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.SetRankingProfileDrv(ctx, args.RankingProfile); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetRankingProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheRankingProfiles, args.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetRanking(ctx *context.Context, args *utils.RankingWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaRankings)
	if err != nil {
		return err
	}
	if err := dataDB.SetRankingDrv(ctx, args.Ranking); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetRanking> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheRankings, args.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetRouteProfile(ctx *context.Context, args *utils.RouteProfileWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaRouteProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.SetRouteProfileDrv(ctx, args.RouteProfile); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetRouteProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheRouteProfiles, args.TenantID(), "", &args.FilterIDs, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetAttributeProfile(ctx *context.Context, args *utils.AttributeProfileWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaAttributeProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.SetAttributeProfileDrv(ctx, args.AttributeProfile); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetAttributeProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheAttributeProfiles, args.TenantID(), "", &args.FilterIDs, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetChargerProfile(ctx *context.Context, args *utils.ChargerProfileWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaChargerProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.SetChargerProfileDrv(ctx, args.ChargerProfile); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetChargerProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheChargerProfiles, args.TenantID(), "", &args.FilterIDs, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) SetActionProfile(ctx *context.Context, args *utils.ActionProfileWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaActionProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.SetActionProfileDrv(ctx, args.ActionProfile); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.SetActionProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheActionProfiles, args.TenantID(), "", &args.FilterIDs, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveAccount(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaAccounts)
	if err != nil {
		return err
	}
	if err := dataDB.RemoveAccountDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveThreshold(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaThresholds)
	if err != nil {
		return err
	}
	if err := dataDB.RemoveThresholdDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveThreshold> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheThresholds, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveThresholdProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaThresholdProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.RemThresholdProfileDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveThresholdProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheThresholdProfiles, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveTrend(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaTrends)
	if err != nil {
		return err
	}
	if err := dataDB.RemoveTrendDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveTrend> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheTrends, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveTrendProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaTrendProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.RemTrendProfileDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveTrendProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheTrendProfiles, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveStatQueue(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaStatQueues)
	if err != nil {
		return err
	}
	if err := dataDB.RemStatQueueDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveStatQueue> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheStatQueues, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveStatQueueProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaStatQueueProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.RemStatQueueProfileDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveStatQueueProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheStatQueueProfiles, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveFilter(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaFilters)
	if err != nil {
		return err
	}
	if err := dataDB.RemoveFilterDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveFilter> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheFilters, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveResource(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaResources)
	if err != nil {
		return err
	}
	if err := dataDB.RemoveResourceDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveResource> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheResources, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveResourceProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaResourceProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.RemoveResourceProfileDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveResourceProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheResourceProfiles, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveIPAllocations(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaIPAllocations)
	if err != nil {
		return err
	}
	if err := dataDB.RemoveIPAllocationsDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveIPAllocations> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheIPAllocations, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveIPProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaIPProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.RemoveIPProfileDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveIPProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheIPProfiles, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveRankingProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaRankingProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.RemRankingProfileDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveRankingProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheRankingProfiles, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveRanking(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaRankings)
	if err != nil {
		return err
	}
	if err := dataDB.RemoveRankingDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveRanking> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheRankings, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveRouteProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaRouteProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.RemoveRouteProfileDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveRouteProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheRouteProfiles, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveAttributeProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaAttributeProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.RemoveAttributeProfileDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveAttributeProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheAttributeProfiles, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveChargerProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaChargerProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.RemoveChargerProfileDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveChargerProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheChargerProfiles, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}

func (r *ReplicatorSv1) RemoveActionProfile(ctx *context.Context, args *utils.TenantIDWithAPIOpts, reply *string) error {
	dataDB, _, err := r.dm.DBConns().GetConn(utils.MetaActionProfiles)
	if err != nil {
		return err
	}
	if err := dataDB.RemoveActionProfileDrv(ctx, args.Tenant, args.ID); err != nil {
		return err
	}
	if r.admin.cfg.GeneralCfg().CachingDelay != 0 {
		utils.Logger.Info(fmt.Sprintf("<ReplicatorSv1.RemoveActionProfile> Delaying cache call for %v", r.admin.cfg.GeneralCfg().CachingDelay))
		time.Sleep(r.admin.cfg.GeneralCfg().CachingDelay)
	}
	if err := r.admin.CallCache(ctx, utils.IfaceAsString(args.APIOpts[utils.MetaCache]),
		args.Tenant, utils.CacheActionProfiles, args.TenantID.TenantID(), "", nil, args.APIOpts); err != nil {
		return err
	}
	*reply = utils.OK
	return nil
}
